FROM oven/bun:1-alpine AS builder
WORKDIR /app

COPY package.json bun.lock ./
COPY packages/shared-types/package.json ./packages/shared-types/
COPY apps/docs/package.json ./apps/docs/
COPY apps/api/package.json ./apps/api/
COPY apps/frontoffice/package.json ./apps/frontoffice/

RUN bun install --frozen-lockfile

COPY tsconfig.base.json ./
COPY packages/shared-types ./packages/shared-types
COPY apps/docs ./apps/docs

WORKDIR /app/apps/docs
RUN bun run build

FROM oven/bun:1-alpine AS runner
WORKDIR /app
COPY --from=builder /app/apps/docs/src/.vitepress/dist ./dist

EXPOSE 3002
CMD ["bun", "x", "serve", "-s", "dist", "-l", "3002"]
