/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalyticsView: typeof import('./src/components/AnalyticsView.vue')['default']
    CreateTokenView: typeof import('./src/components/CreateTokenView.vue')['default']
    ExploreView: typeof import('./src/components/ExploreView.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    TradeView: typeof import('./src/components/TradeView.vue')['default']
  }
}
